
INSERT INTO PUBLIC.ETAT_ACHAT (LIBELLE, DESCRIPTION, TENANT_ID) VALUES ('VALIDEE', null, 'AxelairCorp');
INSERT INTO PUBLIC.ETAT_ACHAT (LIBELLE, DESCRIPTION, TENANT_ID) VALUES ('RETOURNEE', null, 'AxelairCorp');
