create table ETAT_AVOIR
(
    ID INTEGER generated by default as identity primary key,
    LIBELLE VARCHAR(50) not null,
    DESCRIPTION VARCHAR(255),
    TENANT_ID VARCHAR(100) not null,

    constraint FK_ETAT_AVOIR_TENANT
        foreign key (TENANT_ID) references TENANT(ID)
            on delete cascade,

    constraint UK_ETAT_AVOIR
        unique (TENANT_ID, LIBELLE)
);

create index IDX_ETAT_AVOIR_TENANT_ID
    on ETAT_AVOIR (TENANT_ID);

create table AVOIR
(
    ID INTEGER generated by default as identity primary key,
    CLIENT_ID INTEGER not null,
    RETOUR_ID BIGINT not null,
    VENTE_ORIGINE_ID INTEGER not null,
    MONTANT_INITIAL NUMERIC(10,2) not null,
    CREATED_AT TIMESTAMP default CURRENT_TIMESTAMP,
    ETAT_ID INTEGER not null,
    TENANT_ID VARCHAR(100) not null,

    constraint FK_AVOIR_CLIENT
        foreign key (CLIENT_ID) references CLIENTS(ID_CLIENT),

    constraint FK_AVOIR_RETOUR
        foreign key (RETOUR_ID) references RETOUR(ID)
            on delete cascade,

    constraint FK_AVOIR_VENTE
        foreign key (VENTE_ORIGINE_ID) references VENTES(ID_VENTES),

    constraint FK_AVOIR_ETAT
        foreign key (ETAT_ID) references ETAT_AVOIR(ID),

    constraint FK_AVOIR_TENANT
        foreign key (TENANT_ID) references TENANT(ID)
            on delete cascade,

    constraint UK_AVOIR_RETOUR
        unique (RETOUR_ID, TENANT_ID),

    constraint CHK_AVOIR_MONTANT
        check (MONTANT_INITIAL > 0)
);

create index IDX_AVOIR_TENANT_ID
    on AVOIR (TENANT_ID);


create table UTILISATION_AVOIR
(
    ID INTEGER generated by default as identity primary key,
    AVOIR_ID INTEGER not null,
    VENTE_ID INTEGER not null,
    MONTANT_UTILISE NUMERIC(10,2) not null,
    CREATED_AT TIMESTAMP default CURRENT_TIMESTAMP,
    TENANT_ID VARCHAR(100) not null,

    constraint FK_UTIL_AVOIR
        foreign key (AVOIR_ID) references AVOIR(ID)
            on delete cascade,

    constraint FK_UTIL_VENTE
        foreign key (VENTE_ID) references VENTES(ID_VENTES),

    constraint FK_UTIL_TENANT
        foreign key (TENANT_ID) references TENANT(ID)
            on delete cascade,

    constraint CHK_UTIL_AVOIR_MONTANT
        check (MONTANT_UTILISE > 0)
);

create index IDX_UTILISATION_AVOIR_TENANT_ID
    on UTILISATION_AVOIR (TENANT_ID);

alter table LIGNE_RETOUR
    add column PRIX_VENTE_UNITAIRE NUMERIC(10,2);

update LIGNE_RETOUR lr
set PRIX_VENTE_UNITAIRE = (
    select lv.PRIX_VENTE_UNITAIRE
    from LIGNES_VENTES lv
    where lv.ID_LIGNES_VENTES = lr.LIGNE_VENTE_ID
    )
where lr.PRIX_VENTE_UNITAIRE is null;

alter table LIGNE_RETOUR
    alter column PRIX_VENTE_UNITAIRE set not null;

alter table LIGNE_RETOUR
    add constraint CHK_LIGNE_RETOUR_PRIX_POSITIF
        check (PRIX_VENTE_UNITAIRE >= 0);

