-- FK vers CLIENTS
ALTER TABLE VENTES
    ADD CONSTRAINT FK_VENTE_CLIENT
        FOREIGN KEY (CLIENT_ID)
            REFERENCES CLIENTS (ID_CLIENT)
            ON DELETE RESTRICT;

-- FK vers EMPLOYES
ALTER TABLE VENTES
    ADD CONSTRAINT FK_VENTE_EMPLOYE
        FOREIGN KEY (EMPLOYE_ID)
            REFERENCES EMPLOYES (ID_EMPLOYE)
            ON DELETE RESTRICT;

-- FK vers ETAT_VENTE
ALTER TABLE VENTES
    ADD CONSTRAINT FK_VENTE_ETAT
        FOREIGN KEY (ETAT_ID)
            REFERENCES ETAT_VENTE (ID)
            ON DELETE RESTRICT;
