INSERT INTO PUBLIC.ETAT_AVOIR (LIBELLE, DESCRIPTION, TENANT_ID)
VALUES ('ACTIF', 'actif', 'AxelairCorp');

INSERT INTO PUBLIC.ETAT_AVOIR (LIBELLE, DESCRIPTION, TENANT_ID)
VALUES ('PARTIELLEMENT_UTILISE', 'utilisé partielement ', 'AxelairCorp');

INSERT INTO PUBLIC.ETAT_AVOIR (LIBELLE, DESCRIPTION, TENANT_ID)
VALUES ('UTILISE', 'totalement use', 'AxelairCorp');

INSERT INTO PUBLIC.ETAT_AVOIR (LIBELLE, DESCRIPTION, TENANT_ID)
VALUES ('ANNULE', 'annulé donc invalide', 'AxelairCorp');

