DELETE
FROM PUBLIC.ETAT_PAIEMENT
WHERE ID = 2;

DELETE
FROM PUBLIC.ETAT_PAIEMENT
WHERE ID = 3;

DELETE
FROM PUBLIC.ETAT_PAIEMENT
WHERE ID = 5;

DELETE
FROM PUBLIC.ETAT_PAIEMENT
WHERE ID = 1;

INSERT INTO PUBLIC.ETAT_PAIEMENT (LIBELLE, DESCRIPTION, TENANT_ID)
VALUES ('SUCCES', 'succès', 'AxelairCorp');

