INSERT INTO PUBLIC.TENANT (ID, NAME, IS_ACTIVE, CREATED_AT)
VALUES ('AxelairCorp', 'AxelairCorp', DEFAULT, DEFAULT);




INSERT INTO PUBLIC.CATEGORIE (tenant_id, NOM, DESCRIPTION, CREATED_AT, UPDATED_AT) VALUES ('AxelairCorp','Accessoires Téléphone', 'Tous les accessoires pour téléphones mobiles : étuis, chargeurs, câbles, coques, etc.', '2025-01-25 10:21:29.823468', '2025-01-25 10:21:29.823468');
INSERT INTO PUBLIC.CATEGORIE (tenant_id, NOM, DESCRIPTION, CREATED_AT, UPDATED_AT) VALUES ('AxelairCorp','Maison', 'Articles pour la maison : décoration, meubles, luminaires, etc.', '2025-01-25 10:21:29.823468', '2025-01-25 10:21:29.823468');
INSERT INTO PUBLIC.CATEGORIE (tenant_id, NOM, DESCRIPTION, CREATED_AT, UPDATED_AT) VALUES ('AxelairCorp','Bazar', 'Produits divers et variés pour le quotidien : articles de loisir, petits gadgets, etc.', '2025-01-25 10:21:29.823468', '2025-01-25 10:21:29.823468');
INSERT INTO PUBLIC.CATEGORIE (tenant_id, NOM, DESCRIPTION, CREATED_AT, UPDATED_AT) VALUES ('AxelairCorp','Cuisine', 'Équipements et accessoires pour la cuisine : ustensiles, électroménagers, vaisselle, etc.', '2025-01-25 10:21:29.823468', '2025-01-25 10:21:29.823468');
INSERT INTO PUBLIC.CATEGORIE (tenant_id, NOM, DESCRIPTION, CREATED_AT, UPDATED_AT) VALUES ('AxelairCorp','Télévision', 'Produits liés à la télévision : TV, supports, télécommandes, etc.', '2025-01-25 10:21:29.823468', '2025-01-25 10:21:29.823468');
INSERT INTO PUBLIC.CATEGORIE (tenant_id, NOM, DESCRIPTION, CREATED_AT, UPDATED_AT) VALUES ('AxelairCorp','Écrans', 'Tous types d’écrans : moniteurs, écrans d’ordinateur, projecteurs, etc.', '2025-01-25 10:21:29.823468', '2025-01-25 10:21:29.823468');
INSERT INTO PUBLIC.CATEGORIE (tenant_id, NOM, DESCRIPTION, CREATED_AT, UPDATED_AT) VALUES ('AxelairCorp','Matériel Informatique', 'Tout le matériel nécessaire pour l’informatique : ordinateurs, périphériques, composants, etc.', '2025-01-25 10:21:29.823468', '2025-01-25 10:21:29.823468');
INSERT INTO PUBLIC.CATEGORIE (tenant_id, NOM, DESCRIPTION, CREATED_AT, UPDATED_AT) VALUES ('AxelairCorp','Électronique', 'Produits électroniques divers : objets connectés, gadgets électroniques, appareils audio-vidéo, etc.', '2025-01-25 10:21:29.823468', '2025-01-25 10:21:29.823468');


INSERT INTO PUBLIC.CLIENTS (tenant_id, NOM, PRENOM, EMAIL, TELEPHONE, ADRESSE, CREATED_AT, UPDATED_AT, ACTIF) VALUES ('AxelairCorp','Client Junior  ', 'Super client', 'client-junior@gmail.com', '0749482336', null, '2025-02-21 21:51:36.000000', '2025-01-12 10:05:41.163419', true);


INSERT INTO PUBLIC.EMPLOYES (tenant_id, NOM, PRENOM, CREATED_AT, UPDATED_AT, PASSWORD, ACTIF) VALUES ('AxelairCorp','junior', 'junior', '2025-02-10 22:39:42.907528', '2025-02-10 22:39:43.047566', '$2a$10$YLBqIlUvkMk6nOR9tKBPL.jf.H9bT1X8tbGHXx.Y7tVJVuNrgc..q', true);

INSERT INTO PUBLIC.ETAT_PANIER (tenant_id, LIBELLE) VALUES ('AxelairCorp','EN_COURS');
INSERT INTO PUBLIC.ETAT_PANIER (tenant_id, LIBELLE) VALUES ('AxelairCorp','VALIDE');
INSERT INTO PUBLIC.ETAT_PANIER (tenant_id, LIBELLE) VALUES ('AxelairCorp','ANNULE');

INSERT INTO ETAT_VENTE (tenant_id, LIBELLE, DESCRIPTION) VALUES ('AxelairCorp','CREEE', null);
INSERT INTO ETAT_VENTE (tenant_id, LIBELLE, DESCRIPTION) VALUES ('AxelairCorp','VALIDE', null);
INSERT INTO ETAT_VENTE (tenant_id, LIBELLE, DESCRIPTION) VALUES ('AxelairCorp','CONFIRME', null);
INSERT INTO PUBLIC.ETAT_VENTE (tenant_id, LIBELLE, DESCRIPTION)
VALUES ('AxelairCorp','EN_ATTENTE_PAIEMENT', null);

INSERT INTO PUBLIC.ETAT_VENTE (tenant_id, LIBELLE, DESCRIPTION)
VALUES ('AxelairCorp','PAIEMENT_PARTIEL', null);

INSERT INTO PUBLIC.ETAT_VENTE (tenant_id, LIBELLE, DESCRIPTION)
VALUES ('AxelairCorp','VENTE_A_CREDIT', null);

INSERT INTO PUBLIC.ETAT_VENTE (tenant_id, LIBELLE, DESCRIPTION)
VALUES ('AxelairCorp','PAYEE', null);

INSERT INTO PUBLIC.ETAT_VENTE (tenant_id, LIBELLE, DESCRIPTION)
VALUES ('AxelairCorp','FERMEE', null);

INSERT INTO PUBLIC.ETAT_VENTE (tenant_id, LIBELLE, DESCRIPTION)
VALUES ('AxelairCorp','ANNULEE', null);

INSERT INTO PUBLIC.ETAT_FACTURE (tenant_id, LIBELLE, DESCRIPTION) VALUES ('AxelairCorp','CREEE', null);
INSERT INTO PUBLIC.ETAT_FACTURE (tenant_id, LIBELLE, DESCRIPTION) VALUES ('AxelairCorp','GENEREE', null);




INSERT INTO PUBLIC.ROLES (tenant_id, NOM, DESCRIPTION) VALUES ('AxelairCorp','ADMIN', 'Administrateur ayant tous les droits');
INSERT INTO PUBLIC.ROLES (tenant_id, NOM, DESCRIPTION) VALUES ('AxelairCorp','GESTIONNAIRE_STOCK', 'Responsable de la gestion des stocks');
INSERT INTO PUBLIC.ROLES (tenant_id, NOM, DESCRIPTION) VALUES ('AxelairCorp','VENDEUR', 'Employé chargé des ventes');
INSERT INTO PUBLIC.ROLES (tenant_id, NOM, DESCRIPTION) VALUES ('AxelairCorp','COMPTABLE', 'Responsable des finances');
INSERT INTO PUBLIC.ROLES (tenant_id, NOM, DESCRIPTION) VALUES ('AxelairCorp','Role Test', 'erer');

INSERT INTO public.authority (tenant_id, nom) VALUES ('AxelairCorp','CREER_PRODUIT');
INSERT INTO public.authority (tenant_id, nom) VALUES ('AxelairCorp','SUPPRIMER_PRODUIT');
INSERT INTO public.authority (tenant_id, nom) VALUES ('AxelairCorp','VOIR_PRODUIT');
INSERT INTO public.authority (tenant_id, nom) VALUES ('AxelairCorp','GERER_STOCK');
INSERT INTO public.authority (tenant_id, nom) VALUES ('AxelairCorp','VALIDER_VENTE');
INSERT INTO public.authority (tenant_id, nom) VALUES ('AxelairCorp','GENERER_RAPPORT');

INSERT INTO PUBLIC.ROLE_authority (tenant_id, ID_ROLE, ID_AUTHORITY) VALUES ('AxelairCorp',5, 6);
INSERT INTO PUBLIC.ROLE_authority (tenant_id, ID_ROLE, ID_AUTHORITY) VALUES ('AxelairCorp',5, 4);
INSERT INTO PUBLIC.ROLE_authority (tenant_id, ID_ROLE, ID_AUTHORITY) VALUES ('AxelairCorp',5, 5);
INSERT INTO PUBLIC.ROLE_authority (tenant_id, ID_ROLE, ID_AUTHORITY) VALUES ('AxelairCorp',1, 5);
INSERT INTO PUBLIC.ROLE_authority (tenant_id, ID_ROLE, ID_AUTHORITY) VALUES ('AxelairCorp',1, 1);
INSERT INTO PUBLIC.ROLE_authority (tenant_id, ID_ROLE, ID_AUTHORITY) VALUES ('AxelairCorp',1, 3);
INSERT INTO PUBLIC.ROLE_authority (tenant_id, ID_ROLE, ID_AUTHORITY) VALUES ('AxelairCorp',1, 6);
INSERT INTO PUBLIC.ROLE_authority (tenant_id, ID_ROLE, ID_AUTHORITY) VALUES ('AxelairCorp',1, 2);
INSERT INTO PUBLIC.ROLE_authority (tenant_id, ID_ROLE, ID_AUTHORITY) VALUES ('AxelairCorp',1, 4);


INSERT INTO PUBLIC.ROLE_EMPLOYE (tenant_id, ID_ROLE, ID_EMPLOYE) VALUES ('AxelairCorp',1, 1);
INSERT INTO PUBLIC.ROLE_EMPLOYE (tenant_id, ID_ROLE, ID_EMPLOYE) VALUES ('AxelairCorp',2, 1);
INSERT INTO PUBLIC.ROLE_EMPLOYE (tenant_id, ID_ROLE, ID_EMPLOYE) VALUES ('AxelairCorp',3, 1);
INSERT INTO PUBLIC.ROLE_EMPLOYE (tenant_id, ID_ROLE, ID_EMPLOYE) VALUES ('AxelairCorp',4, 1);



INSERT INTO PUBLIC.TYPES_MOUVEMENT_STOCK (tenant_id, CODE, NOM, DESCRIPTION, DATE_CREATION, TYPE_MOUVEMENT) VALUES ('AxelairCorp','DESTRUCTION_PRODUIT', 'Destruction de produit', 'Sortie de stock pour destruction de produits périmés ou endommagés', '2025-01-29 03:37:46.183956', 'SORTIE');
INSERT INTO PUBLIC.TYPES_MOUVEMENT_STOCK (tenant_id, CODE, NOM, DESCRIPTION, DATE_CREATION, TYPE_MOUVEMENT) VALUES ('AxelairCorp','PERTE_VOL', 'Perte ou vol', 'Sortie de stock en raison d’une perte ou d’un vol', '2025-01-29 03:37:46.183956', 'SORTIE');
INSERT INTO PUBLIC.TYPES_MOUVEMENT_STOCK (tenant_id, CODE, NOM, DESCRIPTION, DATE_CREATION, TYPE_MOUVEMENT) VALUES ('AxelairCorp','RETOUR_FOURNISSEUR', 'Retour fournisseur', 'Renvoi d’un produit défectueux ou non conforme au fournisseur', '2025-01-29 03:37:46.183956', 'SORTIE');
INSERT INTO PUBLIC.TYPES_MOUVEMENT_STOCK (tenant_id, CODE, NOM, DESCRIPTION, DATE_CREATION, TYPE_MOUVEMENT) VALUES ('AxelairCorp','TRANSFERT_ENTREPOT', 'Transfert entre entrepôts', 'Mouvement de stock d’un entrepôt à un autre', '2025-01-29 03:37:46.183956', 'SORTIE');
INSERT INTO PUBLIC.TYPES_MOUVEMENT_STOCK (tenant_id, CODE, NOM, DESCRIPTION, DATE_CREATION, TYPE_MOUVEMENT) VALUES ('AxelairCorp','DON_ASSOCIATION', 'Don à une association', 'Sortie de stock pour don à une organisation caritative', '2025-01-29 03:37:46.183956', 'SORTIE');
INSERT INTO PUBLIC.TYPES_MOUVEMENT_STOCK (tenant_id, CODE, NOM, DESCRIPTION, DATE_CREATION, TYPE_MOUVEMENT) VALUES ('AxelairCorp','ACHAT_MARCHANDISE', 'Achat de marchandises', 'Entrée de stock suite à un achat auprès d’un fournisseur', '2025-01-29 03:37:46.183956', 'ENTREE');
INSERT INTO PUBLIC.TYPES_MOUVEMENT_STOCK (tenant_id, CODE, NOM, DESCRIPTION, DATE_CREATION, TYPE_MOUVEMENT) VALUES ('AxelairCorp','INVENTAIRE_AJUSTEMENT', 'Ajustement d’inventaire', 'Correction du stock après un inventaire physique', '2025-01-29 03:37:46.183956', 'ENTREE');
INSERT INTO PUBLIC.TYPES_MOUVEMENT_STOCK (tenant_id, CODE, NOM, DESCRIPTION, DATE_CREATION, TYPE_MOUVEMENT) VALUES ('AxelairCorp','RETOUR_CLIENT', 'Retour client', 'Retour en stock des produits renvoyés par un client', '2025-01-29 03:37:46.183956', 'ENTREE');
INSERT INTO PUBLIC.TYPES_MOUVEMENT_STOCK (tenant_id, CODE, NOM, DESCRIPTION, DATE_CREATION, TYPE_MOUVEMENT) VALUES ('AxelairCorp','RECEPTION_TRANSFERT', 'Réception de transfert', 'Entrée de stock suite à un transfert provenant d’un autre entrepôt', '2025-01-29 03:37:46.183956', 'ENTREE');
INSERT INTO PUBLIC.TYPES_MOUVEMENT_STOCK (tenant_id, CODE, NOM, DESCRIPTION, DATE_CREATION, TYPE_MOUVEMENT) VALUES ('AxelairCorp','VENTE_PRODUIT', 'Vente de produits', 'Sortie de stock pour la vente de produits aux clients', '2025-01-29 03:37:46.183956', 'SORTIE');


INSERT INTO PUBLIC.ETAT_PAIEMENT (tenant_id, LIBELLE, DESCRIPTION)
VALUES ('AxelairCorp','EN_ATTENTE_PAIEMENT', null);

INSERT INTO PUBLIC.ETAT_PAIEMENT (tenant_id, LIBELLE, DESCRIPTION)
VALUES ('AxelairCorp','PAIEMENT_PARTIEL', null);

INSERT INTO PUBLIC.ETAT_PAIEMENT (tenant_id, LIBELLE, DESCRIPTION)
VALUES ('AxelairCorp','VENTE_A_CREDIT', null);

INSERT INTO PUBLIC.ETAT_PAIEMENT (tenant_id, LIBELLE, DESCRIPTION)
VALUES ('AxelairCorp','PAYEE', null);

INSERT INTO PUBLIC.ETAT_PAIEMENT (tenant_id, LIBELLE, DESCRIPTION)
VALUES ('AxelairCorp','FERMEE', null);

INSERT INTO PUBLIC.ETAT_PAIEMENT (tenant_id, LIBELLE, DESCRIPTION)
VALUES ('AxelairCorp','ANNULEE', null);

INSERT INTO PUBLIC.PRODUITS (tenant_id, REFERENCE, NOM, DESCRIPTION, PRIX_ACHAT, PRIX_VENTE, SOUS_CATEGORIE, MARQUE, UNITE_MESURE,
                             SEUIL_LOT, SEUIL_PRODUIT, CREATED_AT, UPDATED_AT, IMAGE, STOCK_INITIAL, QR_CODE, EAN13,
                             CATEGORIE_ID, ACTIF)
VALUES ('AxelairCorp',null, 'Produit', 'test', 2.00, 6.00, null, null, null, 0, null, '2025-05-03 14:56:34.955467',
        '2025-05-03 14:56:34.955467', '', 5,
        '89504E470D0A1A0A0000000D49484452000000640000006401000000005899A8F9000000BA49444154785EE5D2B10D84300C0550A30CC00291320A2B5D1638740B5C5672E735905880742E22F98C0E080D263D569A57D9DF0EC8A916789A103A2C2F80F15624994B94D22088E423FA36CDB95118DA2459F4D5C92EA5F9C89FD35E4A8BC3B1334BE83285B4CF6289CA7BD037DD0B7D27058EC90CD1D44BE9A541ACF95CA2AD83252D94C4F33F9F25DD19CB07F74D185AEF0070A4B50451DC32D44B5B42F982DB3AD8A2397168906484C875B24BADFF0546DE3A58AAF568FD00EB151EFCC96903A20000000049454E44AE426082',
        '9996804452255', 2, true);

INSERT INTO PUBLIC.TARIF_ACHAT (tenant_id,ID_PRODUIT, PRIX_ACHAT, CREATED_AT, UPDATED_AT) VALUES ('AxelairCorp',1, 2.00, '2025-05-03 14:28:26.161295', null);


INSERT INTO PUBLIC.ETAT_ACHAT (tenant_id, LIBELLE, DESCRIPTION) VALUES ('AxelairCorp','CREEE', null);
INSERT INTO PUBLIC.ETAT_ACHAT (tenant_id, LIBELLE, DESCRIPTION) VALUES ('AxelairCorp','VALIDE', null);
INSERT INTO PUBLIC.ETAT_ACHAT (tenant_id, LIBELLE, DESCRIPTION) VALUES ('AxelairCorp','CONFIRME', null);
INSERT INTO PUBLIC.ETAT_ACHAT (tenant_id, LIBELLE, DESCRIPTION) VALUES ('AxelairCorp','ANNULEE', null);
INSERT INTO PUBLIC.ETAT_ACHAT (tenant_id, LIBELLE, DESCRIPTION) VALUES ('AxelairCorp','REMBOURSEE', null);
