INSERT INTO ETAT_VENTE (LIBELLE, DESCRIPTION) VALUES ('CREEE', null);
INSERT INTO ETAT_VENTE (LIBELLE, DESCRIPTION) VALUES ('VALIDE', null);
INSERT INTO ETAT_VENTE (LIBELLE, DESCRIPTION) VALUES ('CONFIRME', null);
INSERT INTO ETAT_VENTE (LIBELLE, DESCRIPTION) VALUES ('ANNULEE', null);
INSERT INTO ETAT_VENTE (LIBELLE, DESCRIPTION) VALUES ('REMBOURSEE', null);

INSERT INTO PUBLIC.ETAT_FACTURE (LIBELLE, DESCRIPTION) VALUES ('CREEE', null);
INSERT INTO PUBLIC.ETAT_FACTURE (LIBELLE, DESCRIPTION) VALUES ('GENEREE', null);

drop table ETAT;

